version: 0.2

phases:
  install:
    runtime-version:
      java: coreto11
  pre_build:
    commands:
      - mvn -B -DskipTests clean package
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - echo finished building

cache:
  paths:
    - '.m2/'