version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
workflows:
  ci-flow:
    jobs:
      - build-and-test
      - aws-ecr/build-and-push-image
        requires:
          - build-and-test
        account-url: AWS_ECR_ACCOUNT_URL
        aws-access-key-id: ACCESS_KEY_ID
        aws-secret-access-key: SECRET_ACCESS_KEY
        checkout: false
        create-repo: true
        repo: AWS_ECR_REPOSITORY_NAME
        tag: 'latest,circleci'
        region: AWS_REGION
        no-output-timeout: 20m